language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

matrix:
    include:
        - php: 5.6
          env: dependencies="--prefer-lowest --prefer-stable" PHP_BIN=php

script:
    - vendor/bin/tester -p $PHP_BIN tests -s
    - php code-checker/src/code-checker.php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - if [ $TRAVIS_PHP_VERSION == "5.3.3" ]; then composer --global config disable-tls true; composer --global config secure-http false; fi
    - travis_retry composer update --no-interaction --prefer-dist $dependencies
    - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
